import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider, UserButton, currentUser } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const user = await currentUser()

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <span>Hello, {user?.firstName || `Stranger`}</span> <UserButton />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
