import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import {
  ClerkProvider,
  MultisessionAppSupport,
  SignedIn,
  UserButton,
  currentUser
} from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Remult Next.js Todos",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const user = await currentUser()

  return (
    <ClerkProvider>
      <MultisessionAppSupport>
        <html lang="en">
          <body className={inter.className}>
            <header>
              <span>Hello, {user?.firstName || `Stranger`}</span>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </header>
            {children}
          </body>
        </html>
      </MultisessionAppSupport>
    </ClerkProvider>
  )
}
